version: '3.8'

services:

  apache:
    container_name: avy-apache-httpd
    build:
      context: ./apache
    volumes:
    - ./apache/configs/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./apache/configs/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    - ./apache/logs:/usr/local/apache2/logs
    - ./web-sites/avy/htdocs:/usr/local/apache2/htdocs/avy
    - ./web-sites/avy-search/htdocs:/usr/local/apache2/htdocs/search-avy
    ports:
    - "80:80"
    networks:
      - 'LAMP'

networks:
  LAMP:
    name: LAMP
