version: '3.8'

services:

  php8.1:
    container_name: avy-search-php
    build:
      context: ./php/dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./htdocs:/var/www/html
    networks:
      - 'LAMP'

  elasticsearch:
    container_name: avy-search-elasticsearch
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    init: true
    environment:
      - node.name=catalog_es1
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      #      - ./elasticsearch/data/:/usr/share/elasticsearch/data
      - ./elasticsearch/log/:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    networks:
      - 'LAMP'

  kibana:
    container_name: avy-search-kibana
    image: kibana:${ELASTICSEARCH_VERSION}
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - server.host=127.0.0.1
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    networks:
      - 'LAMP'
    ports:
      - "5601:5601"

  mariadb:
    container_name: avy-search-mariadb
    build:
      context: ./mariadb
    user: ${UID}:${GID}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
    ports:
      - '3308:3306'
    volumes:
      - './mariadb/data:/var/lib/mysql'
      - './mariadb/logs:/var/log/mysql'
    networks:
      - 'LAMP'

networks:
  LAMP:
    name: LAMP
