version: '3.8'

services:

  php8.1:
    container_name: avy-search-php
    build:
      context: ./php
      dockerfile: ${ENV}.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./htdocs:/var/www/html
    networks:
      - 'LAMP'

  setup_elk:
    build:
      context: ELK/setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./ELK/setup:/state:Z
    environment:
      ELASTICSEARCH_HOST: avy-search-elasticsearch
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_PASSWORD}
    networks:
      - LAMP
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: avy-search-elasticsearch
    image: elasticsearch:${ELASTIC_VERSION}
    init: true
    environment:
      - node.name=catalog_es1
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.max_initial_line_length=10kb
      - action.destructive_requires_name=false
    volumes:
      - ./ELK/elasticsearch/data/:/usr/share/elasticsearch/data
      - ./ELK/elasticsearch/log/:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    networks:
      - 'LAMP'

  kibana:
    container_name: avy-search-kibana
    image: kibana:${ELASTIC_VERSION}
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://avy-search-elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - 'LAMP'
    ports:
      - "5601:5601"

  mariadb:
    container_name: avy-search-mariadb
    build:
      context: ./mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: '*'
    ports:
      - '3310:3306'
    volumes:
      - './mariadb/data:/var/lib/mysql'
      - './mariadb/logs:/var/log/mysql'
    networks:
      - 'LAMP'

networks:
  LAMP:
    name: LAMP
