version: '3.8'

services:

  php8.1:
    container_name: avy-php
    build:
      context: ./php/dev
      args:
        - UID=${UID:-$(id -u)}
        - GID=${GID:-$(id -g)}
    volumes:
      - ./htdocs:/var/www/html
    networks:
      - 'LAMP'

  mysql:
    container_name: avy-mariadb
    build:
      context: ./mysql
    user: "${UID:-$(id -u):${GID:-$(id -g)}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - '3308:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/logs:/var/log/mysql'
    networks:
      - 'LAMP'

networks:
  LAMP:
    name: LAMP
