version: '3.8'

volumes:
    avy_mariadb_data:
      driver: local

services:

  php8.1:
    container_name: avy-php
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./php
      dockerfile: ${ENV}.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./htdocs:/var/www/html
      - ./avy-products:/var/www/content
    networks:
      - 'LAMP'

  mariadb:
    container_name: avy-mariadb
    build:
      context: ./mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: '%'
    ports:
      - '127.0.0.1:3308:3306'
    volumes:
      - 'avy_mariadb_data:/var/lib/mysql'
      - './mariadb/logs:/var/log/mysql'
    networks:
      - 'LAMP'

networks:
  LAMP:
    name: LAMP