version: '3.8'

services:

  php8.1:
    container_name: avy-php
    build:
      context: ./php
      dockerfile: ${ENV}.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./htdocs:/var/www/html
    networks:
      - 'LAMP'

  mariadb:
    container_name: avy-mariadb
    build:
      context: ./mariadb
    user: ${UID:-1000}:${GID:-1000}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: '%'
    ports:
      - '3308:3306'
    volumes:
      - './mariadb/data:/var/lib/mysql'
      - './mariadb/logs:/var/log/mysql'
    networks:
      - 'LAMP'

networks:
  LAMP:
    name: LAMP