version: '3.8'

services:

  php8.1:
    container_name: avy-search-php
    build:
      context: ./php/dev
    volumes:
      - ./htdocs:/var/www/html
    networks:
      - 'LAMP'

  mysql:
    container_name: avy-search-mariadb
    build:
      context: ./mysql
    environment:
      MARIADB_DATABASE: 'avy'
      MARIADB_USER: 'admin'
      MARIADB_PASSWORD: '123123'
      MARIADB_ROOT_PASSWORD: '123123'
      MARIADB_ROOT_HOST: '%'
    ports:
      - '3308:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/logs:/var/log/mysql'
    networks:
      - 'LAMP'

networks:
  LAMP:
    name: LAMP
